# scan_filter_chain:
# - name: angle
#   type: laser_filters/LaserScanAngularBoundsFilter
#   params:
#     lower_angle: 0
#     upper_angle: 3.14

scan_filter_chain:
  # Remove 0°–45° (front-right)
  - name: remove_front_right
    type: laser_filters/LaserScanAngularBoundsFilter
    params:
      lower_angle: 0.0
      upper_angle: 0.785   # ≈45°
      invert: true

  # # Remove 90°–180° (left side front)
  # - name: remove_front_left
  #   type: laser_filters/LaserScanAngularBoundsFilter
  #   params:
  #     lower_angle: 1.57
  #     upper_angle: 3.14   # ≈180°
  #     invert: true

