# scan_filter_chain:
# - name: angle
#   type: laser_filters/LaserScanAngularBoundsFilter
#   params:
#     lower_angle: 0
#     upper_angle: 3.14

scan_filter_chain:

- name: angle2
  type: laser_filters/LaserScanAngularBoundsFilter
  params:
    lower_angle:   -3.14
    upper_angle:  -0.785

